#!/bin/bash
###################################################################################################
#** This file was installed by geo-cli.
#** Do NOT make any changes to this file! It may be overwritten when geo-cli updates.
###################################################################################################
#* Available environment variables:
#   $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
#   $NAUTILUS_SCRIPT_SELECTED_URIS
#   $NAUTILUS_SCRIPT_CURRENT_URI
#   $NAUTILUS_SCRIPT_WINDOW_GEOMETRY

# Open interactive terminal and run geo command.
# the -i option makes bash run in interactive mode. This mode sources the .bashrc file, making geo for us to use.
gnome-terminal -- bash -i -c "geo init repo; echo -e\"\nPress Enter to exit\"; read"
